# Generated by Django 4.2.1 on 2023-06-04 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accsess',
            fields=[
                ('access_code', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('layer_id', models.CharField(primary_key=True, serialize=False)),
                ('table_name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='ProfileUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LayerAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layer_accsses', to='profiles.accsess')),
                ('layer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layer_accsses', to='profiles.layer')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layer_accsses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
