# Generated by Django 4.2.1 on 2023-06-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_layer_layer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='layer_id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
