# Generated by Django 4.2.1 on 2023-06-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_layer_layer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='table_fields',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
