# Generated by Django 4.2.1 on 2023-07-08 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_layer_table_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileuser',
            name='age',
        ),
    ]
