# Generated by Django 4.2.1 on 2023-07-08 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_remove_profileuser_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileuser',
            name='created_at',
        ),
    ]
